### ISSUE TITLE
timer can only be started from the main thread

### ISSUE THREAD

**Issue by Andre9642** [kvark128/WlanReporter#1]
Hello,
First, thanks a lot for this add-on!
I receive this error after network connection/disconnection notifications:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\Users\andre\AppData\Roaming\nvda\addons\WlanReporter\globalPlugins\WlanReporter\__init__.py", line 33, in notifyHandler
    ui.message(_("Connected to {}").format(ssid.decode("utf-8")))
  File "ui.pyc", line 78, in message
  File "braille.pyc", line 1868, in message
  File "braille.pyc", line 1882, in _resetMessageTimer
  File "wx\core.pyc", line 3284, in __init__
  File "wx\core.pyc", line 3305, in Start
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\common\timerimpl.cpp(60) in wxTimerImpl::Start(): timer can only be started from the main thread
```

**Comment by kvark128** [comment]
Thank you for reporting the bug. This is fixed in this version:
https://github.com/kvark128/WlanReporter/releases/download/2020.03.20/WlanReporter-2020.03.20.nvda-addon

**Comment by Andre9642** [comment]
Great! I confirm, it's fixed :)
